### ISSUE TITLE
Mission introduction is unreadable (black-on-black)

### ISSUE THREAD

**Issue by kuhrusty** [nibuen/SpaceAlertMissionGenerator#32]
**The short version:** if you select a mission with an introduction (one of the double-action missions), the introduction is displayed with black text on a black background.  (If you're not seeing this, I can add a screen capture.)

**The long & boring version:** when I merged the `circleci-project-setup` changes into my issue #28 changes, the app didn't look right, & I assumed this was because I'd goofed up one of the conflicts.  So, on my box, in a new clone of my fork, I did this:

    $ git remote add upstream https://github.com/nibuen/SpaceAlertMissionGenerator.git
    $ git remote -v
    origin  https://github.com/kuhrusty/SpaceAlertMissionGenerator.git (fetch)
    origin  https://github.com/kuhrusty/SpaceAlertMissionGenerator.git (push)
    upstream        https://github.com/nibuen/SpaceAlertMissionGenerator.git (fetch)
    upstream        https://github.com/nibuen/SpaceAlertMissionGenerator.git (push)

    $ git fetch upstream

Then I created a branch at the point where I originally forked it, and merged your master into that:

    $ git checkout -b issue28-merge a44ffe9a2c8db53b994d4e57a3b8463adb4dd721 
    $ git merge upstream/master

That fast-forwarded everything.  Now my [issue28-merge branch](/kuhrusty/SpaceAlertMissionGenerator/tree/issue28-merge) *should* be identical to your master; that branch is what I built out of.  (I figure I'll manually merge my issue #28 changes into there, and then do a PR from there.)

**Comment by nibuen** [comment]
Thanks!  I did have to retheme everything with the upgrades, so thought I might miss a few passes,, lets get your stuff merged and then will do some extensive testing as well

**Comment by nibuen** [comment]
I think also it was cause my phone is in dark mode theme... need to check for more consistent compatibility on that

**Comment by kuhrusty** [comment]
> lets get your stuff merged

OK, should be sending a PR in the next hour or so.
