### ISSUE TITLE
SeekBarPreference illegible with light theme

### ISSUE THREAD

**Issue by kuhrusty** [nibuen/SpaceAlertMissionGenerator#36]
On my Android 9 phone, the theme is now light, so the background of the SeekBarPreference window is white, so the `android:textColor="@color/white_color"` in `dialog_slider.xml` no longer shows up.

(If I could go back to the old dark theme, I'd prefer it! but I [get the impression](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme) I can't do that unless I have an Android 10 device.)

![ss1 25](https://user-images.githubusercontent.com/10725505/89706857-56661b80-d91e-11ea-8395-cd85ce201c07.jpg)

**Comment by nibuen** [comment]
I think i can make it default pre Android 10 devices, I agree let me figure out how to do that as well as fixing this
