### ISSUE TITLE
Light theme is rough in MissionActivity

### ISSUE THREAD

**Issue by kuhrusty** [nibuen/SpaceAlertMissionGenerator#37]
As mentioned in issue #36, I think I'm stuck using a light theme? and I find it a lot harder to read than the old dark theme:

![ss2 25](https://user-images.githubusercontent.com/10725505/89707046-bc06d780-d91f-11ea-95d1-6ae9a1987a5b.jpg)

My first choice would be to go back to the old dark theme.  My second choice--if I *must* use a light theme!--would maybe be to have a light gray background and white card backgrounds?  (And maybe darker text, depending on how that looks.)

**Comment by nibuen** [comment]
Agreed need to make Dark theme default,  I might just force it back even for now.  Will play with it a bit more.
