### ISSUE TITLE
SeekBarPreference: tapping on scroll bar track should move knob

### ISSUE THREAD

**Issue by kuhrusty** [nibuen/SpaceAlertMissionGenerator#39]
This is probably one of those Android UI things which *should* take 10 minutes but instead takes 3 hours, but it would be nice if tapping on the scroll bar track jumped the knob along the track.  So, for example, if you're looking at the Players SeekBarPreference which goes from 1 to 5, and it's on 4, tapping anywhere on the track to the right of the knob should move the knob to 5, and tapping anywhere to the left should move it to 3.

(For SeekBarPreferences with both knobs, we would probably ignore taps between the knobs; or, maybe we would move the closest knob.)

My feelings will not be hurt if you reject this; it's probably a dumb amount of work for approximately zero benefit.  Maybe we could make the intern do it?

**Comment by nibuen** [comment]
haha, where them interns!  I agree, I actually hate the seekbar in general =/  need to check for something better...
