### ISSUE TITLE
Generated number of threats is one lower than requested

### ISSUE THREAD

**Issue by phantomwhale** [nibuen/SpaceAlertMissionGenerator#53]
# Problem

When running a "random" mission, we are getting one less threat point worth of threats than requested

Running the latest version on Google Play store, on a Pixel 3a

# To recreate

Open the app, select:
* Players: 4
* Stomp Unconfirmed Reports: On
* Threat difficulty: 8
* Dump Mission tree: On (for quicker debugging - so useful, thanks!)

Now start a new "random" mission. 

Mission will always contain 7 points of threats, not 8.

**Comment by phantomwhale** [comment]
I do wonder if this is because we are 4 players and stomping unconfirmed reports (e.g. so with unconfirmed reports not stomped, we would have the 8 points of threat we requested, it's just that one of them would be unconfirmed?)

**Comment by nibuen** [comment]
This is as expected, and do to the stomping uncofirmed.

**Comment by phantomwhale** [comment]
Ha, thanks for checking back in on this one 😅
