### ISSUE TITLE
Translating Store Listing to German

### ISSUE THREAD

**Issue by nibuen** [nibuen/SpaceAlertMissionGenerator#6]
Currently the application has been translated to German, but store listing still has no german translation.

These are the phrases needed to be translated:

1. Space Alert Mission Generator

2. Mission Generator for Space Alert Board Game.

3. Note: This is NOT a game, but instead a tool to be used with the board game Space Alert.  Space Alert is a cooperative board game by Vlaada Chvátil. This app will generate random missions to use in that game, and will assist with the walk-through after each mission is completed.

**Comment by Na-Ich** [comment]
Hi there,
i tried to translate these for you. I'm a german native speaker, I hope my english is good enough.


    Space Alert Mission Generator
Missionsgenerator für Space Alert

    Mission Generator for Space Alert Board Game.
Missionsgenerator zur Verwendung mit dem Brettspiel "Space Alert"

Note: This is NOT a game, but instead a tool to be used with the board game Space Alert.
Anmerkung: Dies ist KEIN selbstständiges Spiel, vielmehr ist es ein Hilfsmittel zur Verwendung mit dem Brettspiel "Space Alert"

Space Alert is a cooperative board game by Vlaada Chvátil. This app will generate random missions to use in the game, or let you play with the original missions that came with the game, including the missions from the expansion Space Alert: The New Frontier.
Space Alert ist ein kooperatives Brettspiel von Vlaada Chvátil. Diese Aplikation erstellt zufallsgenerierte Missionen oder spielt die vorgegebenen Missionen aus dem Basisspiel oder der Erweiterung "Space Alert: The New Frontier" ab.

The app will assist with the walk-through after each mission is completed by keeping a mission log of all the events from the mission.
Die Applikation listet eine Missionszusammenfassung auf, mit deren Hilfe die Ausführungsrunde erleichtert wird.

It is not possible to generate random missions for Double Action cards from the expansion.
Es ist zur Zeit nicht möglich Zufallsmissionen für die Verwendung der Doppelaktionskarten aus der Erweiterung zu erstellen.

**Comment by nibuen** [comment]
Awesome thanks will get it up!

**Comment by nibuen** [comment]
resolved
